modLoader="javafml"
loaderVersion="${loader_range}"
license="MIT, https://spdx.org/licenses/MIT.html"
issueTrackerURL="https://github.com/Pyre540/tinkers-levelling-addon/issues"

[[mods]]
modId="tinkerslevellingaddon"
version="${file.jarVersion}"
displayName="Tinkers Levelling Addon"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Pyre540" #optional
description='''
Tinkers Construct addon that adds tool leveling system.
'''

[[dependencies.tinkerslevellingaddon]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tinkerslevellingaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tinkerslevellingaddon]]
    modId="tconstruct"
    mandatory=true
    versionRange="${tinkers_range}"
    ordering="NONE"
    side="BOTH"